# Generated by Django 4.2.5 on 2023-12-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_address', to='user.usersubscription'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_name', to='user.usersubscription'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_phone_number', to='user.usersubscription'),
        ),
    ]
