# Generated by Django 4.2.6 on 2023-12-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_address_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='personalized_identifier',
            field=models.CharField(default=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user.usersubscription'),
        ),
    ]
