# Generated by Django 4.2.5 on 2023-12-07 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usersubscription_personalized_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
