# Generated by Django 4.2.5 on 2023-12-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_current_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
