# Generated by Django 4.2.5 on 2023-12-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userprofile_current_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='personalized_identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
