# Generated by Django 4.2.5 on 2023-12-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usersubscription_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='type_tea',
            new_name='tea_type',
        ),
    ]
