# Generated by Django 4.2.5 on 2023-12-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_type_tea_usersubscription_tea_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='name',
            new_name='fullname',
        ),
    ]
