# Generated by Django 4.2.5 on 2023-12-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_name_usersubscription_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='days_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
