# Generated by Django 4.2.5 on 2023-11-28 22:42

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='images/flowers.jpeg', upload_to='subscription_images/')),
            ],
            options={
                'verbose_name': 'Подписка на чай',
                'verbose_name_plural': 'Подписки на чай',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория чая',
                'verbose_name_plural': 'Категории чая',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?1?\\d{9,15}$')])),
                ('date_arrive', models.DateTimeField(default=datetime.datetime.now)),
                ('address', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('sub_id', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='tea.subscription')),
            ],
            options={
                'verbose_name': 'UserSubscription',
                'verbose_name_plural': 'UserSubscriptions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('subscription', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_address', to='tea.usersubscription')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_name', to='tea.usersubscription')),
                ('phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_phone_number', to='tea.usersubscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='teas/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teas', to='tea.teacategory')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='teas',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='tea.tea'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tea.subscription')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.tea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Кредитная карта'), ('paypal', 'PayPal'), ('other', 'Другой')], max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено')], max_length=255)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_interval', models.CharField(blank=True, choices=[('monthly', 'Ежемесячно'), ('quarterly', 'Каждые 3 месяца')], max_length=255, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_interval', models.CharField(choices=[('monthly', 'Ежемесячно'), ('quarterly', 'Каждые 3 месяца')], max_length=255)),
                ('tea_format', models.CharField(choices=[('tea_bags', 'Пакетики'), ('loose_leaf', 'Листовой чай')], max_length=255)),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(choices=[('processing', 'Обработка'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено')], max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Кредитная карта'), ('paypal', 'PayPal'), ('other', 'Другой')], max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено')], max_length=255)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.subscription')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.tea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.userprofile')),
            ],
        ),
    ]
