# Generated by Django 4.2.5 on 2023-11-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
