# Generated by Django 4.2.7 on 2023-11-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0002_auto_20231021_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(default='images/flowers.jpeg', upload_to='subscription_images/'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
