# Generated by Django 4.2.5 on 2023-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0003_usersubscription_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='date_arrive',
            field=models.DateField(),
        ),
    ]
