# Generated by Django 4.2.7 on 2023-11-27 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0004_userprofile_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
