# Generated by Django 4.2.5 on 2023-11-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0004_alter_usersubscription_date_arrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='type_tea',
            field=models.IntegerField(default=0),
        ),
    ]
